stages:
    - analysis
    - setup
    - jestTest
    - build
   # - cypressTest

#include:
#    - template: Code-Quality.gitlab-ci.yml

.nodeimage: &nodeimage
    image: node:16.5.0-alpine

#code_quality:
#    stage: analysis

installReactApp:
    stage: setup
    <<: *nodeimage
    script:
        - cd reactApp
        - npm i
    artifacts:
        expire_in: 15 mins
        paths:
            - reactApp/node_modules/

installGameApi:
    stage: setup
    <<: *nodeimage
    script:
        - cd gameApi
        - npm i
    artifacts:
        expire_in: 15 mins
        paths:
            - gameApi/node_modules/

installGraphQLAPI:
    stage: setup
    <<: *nodeimage
    script:
        - cd graphQLAPI
        - npm i
    artifacts:
        expire_in: 15 mins
        paths:
            - graphQLAPI/node_modules/

jestTest:
    stage: jestTest
    <<: *nodeimage
    script:
        - cd reactApp
        - npm t

build:
    stage: build
    <<: *nodeimage
    script:
        - cd reactApp
        - npm run build
    artifacts:
        expire_in: 15 mins
        paths:
            - reactApp/build
#e2eTests:
#    image: docker:19.03.12
#    variables:
#        DOCKER_TLS_CERTDIR: "/certs"
#    stage: cypressTest
#    services:
#        - docker:19.03.12-dind
#    before_script:
#        - apk update
#        - apk add py-pip musl-dev python3-dev libffi-dev openssl-dev gcc libc-dev rust cargo make
#        - pip install docker-compose
#    dependencies:
#        - build
#    services:
#        - docker:dind
#    script:
#       - docker-compose up --abort-on-container-exit --exit-code-from cypress
