version: '3'
services:
        web:
                build: .
                stdin_open: true
                ports:
                        - "3000:3000"
                        - "5000:5000"
                volumes:
                        - .:/guesstimoji
