version: '3'

services:
    game-api:
        # where the dockerfile is
        build: ./gameApi
        #expose:
        #        - 5000
        # ports (HOST:CONTAINER)
        # the application running inside is exposed at port CONTAINER
        #       this step seems to make expose redundant
        # map it through host server port HOST
        # can access with http://{host IP}:HOST
        ports:
            - '5000:5000'
        volumes:
            - ./gameApi:/home/node/gameApi

    graph-ql-api:
        build: ./graphQLAPI
        #expose:
        #        - 5000
        # ports (HOST:CONTAINER)
        # the application running inside is exposed at port CONTAINER
        #       this step seems to make expose redundant
        # map it through host server port HOST
        # can access with http://{host IP}:HOST
        depends_on:
            - mongo
        ports:
            - '3005:3005'
        volumes:
            - ./gameApi:/home/node/gameApi

    mongo:
        image: mongo
        volumes:
            - /var/lib/mongodb:/data/db
        ports:
            - '27018:27017'

    app:
        image: node:latest
        depends_on:
            - graph-ql-api
            - mongo
            - game-api
        ports:
            - '3000:3000'
        volumes:
            - ./build:/home/node/app
