version: '2'

services:
    gameApi:
        image: ${REGISTRY_USER}/guesstimoji-game-api:latest
        #expose:
        #        - 5000
        # ports (HOST:CONTAINER)
        # the application running inside is exposed at port CONTAINER
        #       this step seems to make expose redundant
        # map it through host server port HOST
        # can access with http://{host IP}:HOST
        ports:
            - '5001:5001'

    graphQlApi:
        image: ${REGISTRY_USER}/guesstimoji-graph-ql-api:latest
        #expose:
        #        - 5000
        # ports (HOST:CONTAINER)
        # the application running inside is exposed at port CONTAINER
        #       this step seems to make expose redundant
        # map it through host server port HOST
        # can access with http://{host IP}:HOST
        ports:
            - '3005:3005'

    reactApp:
        image: ${REGISTRY_USER}/guesstimoji-react-app:latest
        depends_on:
            - graphQlApi
            - gameApi
        ports:
            - '80:80'
        command: [nginx, '-g', 'daemon off;']
